name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: spiral-software
  GITHUB_REPOSITORY: spiral-software/fftx
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

##  Temporarily re-gen docs when push to "main" or "develop" branches
on:
  push:
    branches:
      - main
      - develop

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout spiral-software
      uses: actions/checkout@v4
      with:
        repository: spiral-software/spiral-software
        path: spiral
        
    - name: install dependencies
      ##  uses: actions/checkout@v4
      run: |
        set -x
        echo "working dir = ${{ github.workspace }}"
        ls -l spiral
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -qqq update
        sudo apt-get install -y build-essential ca-certificates cmake pkg-config wget
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip
        pip install -U Sphinx 
        PATH=$PATH:/home/runner/.local/bin
        echo $PATH
        pip install sphinx_rtd_theme 
        pip install breathe
        sudo apt-get install -y doxygen
        sudo apt-get install -y graphviz
        sudo apt-get install -y pandoc
        sudo curl -L -o /usr/local/bin/cmake-easyinstall https://git.io/JvLxY
        sudo chmod a+x /usr/local/bin/cmake-easyinstall
        export CEI_SUDO="sudo"

    - name: build SPIRAL executable
      env:
        SPIRAL_HOME: ${{ github.workspace }}/spiral
      run: |
        echo $SPIRAL_HOME
        cd $SPIRAL_HOME
        mkdir build && cd build
        cmake .. 
        make -j 2 install

    - name: Checkout the FFTX repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        path: fftx

    - name: build the docs
      env:
        SPIRAL_HOME: ${{ github.workspace }}/spiral
        FFTX_HOME: ${{ github.workspace }}/fftx
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        ##  echo $PATH
        ##  which dot
        ##  which pandoc
        ##  which doxygen
        PATH=$PATH:/home/runner/.local/bin
        cd $FFTX_HOME
        pandoc --from=gfm --to=rst --output=docs/README.rst README.md
        mkdir build && cd build
        cmake -DFFTX_MAKE_DOCS=True ..
        make Sphinx
        ##  find . -iname namespacefftx.xml
        ##  ls /home/runner/work/fftx/fftx/fftx/build/docs/doxygen/xml
        ##  ls docs
        ##  ls docs/doxygen/xml
        ##  cat docs/doxygen/xml/index.xml
        ##  mv docs/doxygen/html docs/sphinx/html
        ##  # mv /home/runner/work/fftx/fftx/fftx/build/docs/doxygen/html/ /home/runner/work/fftx/fftx/fftx/build/docs/sphinx/html
        ##  ls docs/sphinx
        "../docs/buildsite.sh"
      shell: bash
